server.port: 2001

spring.application.name: business1

eureka.client.serviceUrl.defaultZone: http://localhost:9999/eureka/

contextContainer:

baseConfig:
  beanPath: cn.xj.project.model

spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  profiles:
    active: dev