server.port: 2004

spring.application.name: business4

eureka.client.serviceUrl.defaultZone: http://localhost:9999/eureka/

spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
#  profiles:
#    active: dev
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update