server.port: 1001

spring:
  cloud.config:
    server:
      git:
        uri: http://git.oschina.net/goldkingdom/config-repo/
        search-paths: properties
    enabled: true
  profiles:
    active: dev

eureka:
  instance.hostname: ${spring.application.name}
  client.serviceUrl.defaultZone: http://localhost:9999/eureka/
